excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- EngWordTests
- "R.generated.swift"
disabled_rules:
- identifier_name
- trailing_whitespace
- line_length
- type_name
- switch_case_alignment
- type_body_length
#variable_name:
#max_length:
#    warning: 45
#    error: 60
#min_length:
#    warning: 1


