//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let reuseIdentifier = reuseIdentifier()

  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 28 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: All Topics
      ///
      /// Key: all_topics
      ///
      /// Locales: en, vi
      var all_topics: RswiftResources.StringResource { .init(key: "all_topics", tableName: "Localizable", source: source, developmentValue: "All Topics", comment: nil) }

      /// en translation: Create Folder
      ///
      /// Key: create_new_folder
      ///
      /// Locales: en, vi
      var create_new_folder: RswiftResources.StringResource { .init(key: "create_new_folder", tableName: "Localizable", source: source, developmentValue: "Create Folder", comment: nil) }

      /// en translation: Data Format Not Available
      ///
      /// Key: data_format_not_available
      ///
      /// Locales: en, vi
      var data_format_not_available: RswiftResources.StringResource { .init(key: "data_format_not_available", tableName: "Localizable", source: source, developmentValue: "Data Format Not Available", comment: nil) }

      /// en translation: Definition
      ///
      /// Key: definition
      ///
      /// Locales: en, vi
      var definition: RswiftResources.StringResource { .init(key: "definition", tableName: "Localizable", source: source, developmentValue: "Definition", comment: nil) }

      /// en translation: Done
      ///
      /// Key: done
      ///
      /// Locales: en, vi
      var done: RswiftResources.StringResource { .init(key: "done", tableName: "Localizable", source: source, developmentValue: "Done", comment: nil) }

      /// en translation: Email
      ///
      /// Key: email
      ///
      /// Locales: en, vi
      var email: RswiftResources.StringResource { .init(key: "email", tableName: "Localizable", source: source, developmentValue: "Email", comment: nil) }

      /// en translation: Example
      ///
      /// Key: example
      ///
      /// Locales: en, vi
      var example: RswiftResources.StringResource { .init(key: "example", tableName: "Localizable", source: source, developmentValue: "Example", comment: nil) }

      /// en translation: Favorite
      ///
      /// Key: favorite
      ///
      /// Locales: en, vi
      var favorite: RswiftResources.StringResource { .init(key: "favorite", tableName: "Localizable", source: source, developmentValue: "Favorite", comment: nil) }

      /// en translation: Folder
      ///
      /// Key: folder
      ///
      /// Locales: en, vi
      var folder: RswiftResources.StringResource { .init(key: "folder", tableName: "Localizable", source: source, developmentValue: "Folder", comment: nil) }

      /// en translation: Foleder Name
      ///
      /// Key: folder_name
      ///
      /// Locales: en, vi
      var folder_name: RswiftResources.StringResource { .init(key: "folder_name", tableName: "Localizable", source: source, developmentValue: "Foleder Name", comment: nil) }

      /// en translation: Logout
      ///
      /// Key: logout
      ///
      /// Locales: en, vi
      var logout: RswiftResources.StringResource { .init(key: "logout", tableName: "Localizable", source: source, developmentValue: "Logout", comment: nil) }

      /// en translation: Or
      ///
      /// Key: or
      ///
      /// Locales: en, vi
      var or: RswiftResources.StringResource { .init(key: "or", tableName: "Localizable", source: source, developmentValue: "Or", comment: nil) }

      /// en translation: Password
      ///
      /// Key: password
      ///
      /// Locales: en, vi
      var password: RswiftResources.StringResource { .init(key: "password", tableName: "Localizable", source: source, developmentValue: "Password", comment: nil) }

      /// en translation: Quickly Sign In With
      ///
      /// Key: quickly_signin_with
      ///
      /// Locales: en, vi
      var quickly_signin_with: RswiftResources.StringResource { .init(key: "quickly_signin_with", tableName: "Localizable", source: source, developmentValue: "Quickly Sign In With", comment: nil) }

      /// en translation: Review
      ///
      /// Key: review
      ///
      /// Locales: en, vi
      var review: RswiftResources.StringResource { .init(key: "review", tableName: "Localizable", source: source, developmentValue: "Review", comment: nil) }

      /// en translation: Sign In
      ///
      /// Key: signin
      ///
      /// Locales: en, vi
      var signin: RswiftResources.StringResource { .init(key: "signin", tableName: "Localizable", source: source, developmentValue: "Sign In", comment: nil) }

      /// en translation: You are using app without signing in. You data is at risk of being lost
      ///
      /// Key: signin_note
      ///
      /// Locales: en, vi
      var signin_note: RswiftResources.StringResource { .init(key: "signin_note", tableName: "Localizable", source: source, developmentValue: "You are using app without signing in. You data is at risk of being lost", comment: nil) }

      /// en translation: Sign In Success
      ///
      /// Key: signin_success
      ///
      /// Locales: en, vi
      var signin_success: RswiftResources.StringResource { .init(key: "signin_success", tableName: "Localizable", source: source, developmentValue: "Sign In Success", comment: nil) }

      /// en translation: Sign In With Email
      ///
      /// Key: signin_with_email
      ///
      /// Locales: en, vi
      var signin_with_email: RswiftResources.StringResource { .init(key: "signin_with_email", tableName: "Localizable", source: source, developmentValue: "Sign In With Email", comment: nil) }

      /// en translation: Sign Up
      ///
      /// Key: signup
      ///
      /// Locales: en, vi
      var signup: RswiftResources.StringResource { .init(key: "signup", tableName: "Localizable", source: source, developmentValue: "Sign Up", comment: nil) }

      /// en translation: Study
      ///
      /// Key: study
      ///
      /// Locales: en, vi
      var study: RswiftResources.StringResource { .init(key: "study", tableName: "Localizable", source: source, developmentValue: "Study", comment: nil) }

      /// en translation: Studying
      ///
      /// Key: studying
      ///
      /// Locales: en, vi
      var studying: RswiftResources.StringResource { .init(key: "studying", tableName: "Localizable", source: source, developmentValue: "Studying", comment: nil) }

      /// en translation: Term
      ///
      /// Key: term
      ///
      /// Locales: en, vi
      var term: RswiftResources.StringResource { .init(key: "term", tableName: "Localizable", source: source, developmentValue: "Term", comment: nil) }

      /// en translation: Test
      ///
      /// Key: test
      ///
      /// Locales: en, vi
      var test: RswiftResources.StringResource { .init(key: "test", tableName: "Localizable", source: source, developmentValue: "Test", comment: nil) }

      /// en translation: Trash
      ///
      /// Key: trash
      ///
      /// Locales: en, vi
      var trash: RswiftResources.StringResource { .init(key: "trash", tableName: "Localizable", source: source, developmentValue: "Trash", comment: nil) }

      /// en translation: Type folder name
      ///
      /// Key: type_folder_name
      ///
      /// Locales: en, vi
      var type_folder_name: RswiftResources.StringResource { .init(key: "type_folder_name", tableName: "Localizable", source: source, developmentValue: "Type folder name", comment: nil) }

      /// en translation: Update Folder
      ///
      /// Key: update_folder
      ///
      /// Locales: en, vi
      var update_folder: RswiftResources.StringResource { .init(key: "update_folder", tableName: "Localizable", source: source, developmentValue: "Update Folder", comment: nil) }

      /// en translation: Words
      ///
      /// Key: words
      ///
      /// Locales: en, vi
      var words: RswiftResources.StringResource { .init(key: "words", tableName: "Localizable", source: source, developmentValue: "Words", comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 13 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `active`.
    var active: RswiftResources.ColorResource { .init(name: "active", path: [], bundle: bundle) }

    /// Color `cellBackground`.
    var cellBackground: RswiftResources.ColorResource { .init(name: "cellBackground", path: [], bundle: bundle) }

    /// Color `correct`.
    var correct: RswiftResources.ColorResource { .init(name: "correct", path: [], bundle: bundle) }

    /// Color `daily`.
    var daily: RswiftResources.ColorResource { .init(name: "daily", path: [], bundle: bundle) }

    /// Color `incorrect`.
    var incorrect: RswiftResources.ColorResource { .init(name: "incorrect", path: [], bundle: bundle) }

    /// Color `mainBackground`.
    var mainBackground: RswiftResources.ColorResource { .init(name: "mainBackground", path: [], bundle: bundle) }

    /// Color `mainText`.
    var mainText: RswiftResources.ColorResource { .init(name: "mainText", path: [], bundle: bundle) }

    /// Color `monthly`.
    var monthly: RswiftResources.ColorResource { .init(name: "monthly", path: [], bundle: bundle) }

    /// Color `placeholder`.
    var placeholder: RswiftResources.ColorResource { .init(name: "placeholder", path: [], bundle: bundle) }

    /// Color `separatorLine`.
    var separatorLine: RswiftResources.ColorResource { .init(name: "separatorLine", path: [], bundle: bundle) }

    /// Color `unFocused`.
    var unFocused: RswiftResources.ColorResource { .init(name: "unFocused", path: [], bundle: bundle) }

    /// Color `weekly`.
    var weekly: RswiftResources.ColorResource { .init(name: "weekly", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 34 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `addRoundIcon`.
    var addRoundIcon: RswiftResources.ImageResource { .init(name: "addRoundIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrowDropDown`.
    var arrowDropDown: RswiftResources.ImageResource { .init(name: "arrowDropDown", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `avatar`.
    var avatar: RswiftResources.ImageResource { .init(name: "avatar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `backIcon`.
    var backIcon: RswiftResources.ImageResource { .init(name: "backIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bookCheckIcon`.
    var bookCheckIcon: RswiftResources.ImageResource { .init(name: "bookCheckIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bookIcon`.
    var bookIcon: RswiftResources.ImageResource { .init(name: "bookIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bookOpenIcon`.
    var bookOpenIcon: RswiftResources.ImageResource { .init(name: "bookOpenIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `calendarIcon`.
    var calendarIcon: RswiftResources.ImageResource { .init(name: "calendarIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `calendarLineIcon`.
    var calendarLineIcon: RswiftResources.ImageResource { .init(name: "calendarLineIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `checkRoundFillIcon`.
    var checkRoundFillIcon: RswiftResources.ImageResource { .init(name: "checkRoundFillIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `closeRoundFillIcon`.
    var closeRoundFillIcon: RswiftResources.ImageResource { .init(name: "closeRoundFillIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `closeRoundIcon`.
    var closeRoundIcon: RswiftResources.ImageResource { .init(name: "closeRoundIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `createDateIcon`.
    var createDateIcon: RswiftResources.ImageResource { .init(name: "createDateIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `doneIcon`.
    var doneIcon: RswiftResources.ImageResource { .init(name: "doneIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `folderIcon`.
    var folderIcon: RswiftResources.ImageResource { .init(name: "folderIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fullIcon`.
    var fullIcon: RswiftResources.ImageResource { .init(name: "fullIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `happyFaceIcon`.
    var happyFaceIcon: RswiftResources.ImageResource { .init(name: "happyFaceIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `logOutIcon`.
    var logOutIcon: RswiftResources.ImageResource { .init(name: "logOutIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `moreActionIcon`.
    var moreActionIcon: RswiftResources.ImageResource { .init(name: "moreActionIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `normal`.
    var normal: RswiftResources.ImageResource { .init(name: "normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `paperIcon`.
    var paperIcon: RswiftResources.ImageResource { .init(name: "paperIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pressed`.
    var pressed: RswiftResources.ImageResource { .init(name: "pressed", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sadFaceIcon`.
    var sadFaceIcon: RswiftResources.ImageResource { .init(name: "sadFaceIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `saveFillIcon`.
    var saveFillIcon: RswiftResources.ImageResource { .init(name: "saveFillIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `searchTextIcon`.
    var searchTextIcon: RswiftResources.ImageResource { .init(name: "searchTextIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `setIcon`.
    var setIcon: RswiftResources.ImageResource { .init(name: "setIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sortIcon`.
    var sortIcon: RswiftResources.ImageResource { .init(name: "sortIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sparklesIcon`.
    var sparklesIcon: RswiftResources.ImageResource { .init(name: "sparklesIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `speakerIcon`.
    var speakerIcon: RswiftResources.ImageResource { .init(name: "speakerIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `starIcon`.
    var starIcon: RswiftResources.ImageResource { .init(name: "starIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `trashFillIcon`.
    var trashFillIcon: RswiftResources.ImageResource { .init(name: "trashFillIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `trashLineIcon`.
    var trashLineIcon: RswiftResources.ImageResource { .init(name: "trashLineIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `trophyIcon`.
    var trophyIcon: RswiftResources.ImageResource { .init(name: "trophyIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `victoryIcon`.
    var victoryIcon: RswiftResources.ImageResource { .init(name: "victoryIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
            var uiSceneStoryboardFile: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneStoryboardFile") ?? "Home" }
          }
        }
      }
    }
  }

  /// This `_R.font` struct is generated, and contains static references to 5 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `HindSiliguri-Bold`.
    var hindSiliguriBold: RswiftResources.FontResource { .init(name: "HindSiliguri-Bold", bundle: bundle, filename: "HindSiliguri-Bold.ttf") }

    /// Font `HindSiliguri-Light`.
    var hindSiliguriLight: RswiftResources.FontResource { .init(name: "HindSiliguri-Light", bundle: bundle, filename: "HindSiliguri-Light.ttf") }

    /// Font `HindSiliguri-Medium`.
    var hindSiliguriMedium: RswiftResources.FontResource { .init(name: "HindSiliguri-Medium", bundle: bundle, filename: "HindSiliguri-Medium.ttf") }

    /// Font `HindSiliguri-Regular`.
    var hindSiliguriRegular: RswiftResources.FontResource { .init(name: "HindSiliguri-Regular", bundle: bundle, filename: "HindSiliguri-Regular.ttf") }

    /// Font `HindSiliguri-SemiBold`.
    var hindSiliguriSemiBold: RswiftResources.FontResource { .init(name: "HindSiliguri-SemiBold", bundle: bundle, filename: "HindSiliguri-SemiBold.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [hindSiliguriBold, hindSiliguriLight, hindSiliguriMedium, hindSiliguriRegular, hindSiliguriSemiBold].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 18 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `HindSiliguri-Bold.ttf`.
    var hindSiliguriBoldTtf: RswiftResources.FileResource { .init(name: "HindSiliguri-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `HindSiliguri-Light.ttf`.
    var hindSiliguriLightTtf: RswiftResources.FileResource { .init(name: "HindSiliguri-Light", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `HindSiliguri-Medium.ttf`.
    var hindSiliguriMediumTtf: RswiftResources.FileResource { .init(name: "HindSiliguri-Medium", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `HindSiliguri-Regular.ttf`.
    var hindSiliguriRegularTtf: RswiftResources.FileResource { .init(name: "HindSiliguri-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `HindSiliguri-SemiBold.ttf`.
    var hindSiliguriSemiBoldTtf: RswiftResources.FileResource { .init(name: "HindSiliguri-SemiBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `TwitterHeartButton.json`.
    var twitterHeartButtonJson: RswiftResources.FileResource { .init(name: "TwitterHeartButton", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `confetti-explode.json`.
    var confettiExplodeJson: RswiftResources.FileResource { .init(name: "confetti-explode", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `confetti-sparkle.json`.
    var confettiSparkleJson: RswiftResources.FileResource { .init(name: "confetti-sparkle", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `confetti-with-fireworks.json`.
    var confettiWithFireworksJson: RswiftResources.FileResource { .init(name: "confetti-with-fireworks", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `congratulation-badge-animation.json`.
    var congratulationBadgeAnimationJson: RswiftResources.FileResource { .init(name: "congratulation-badge-animation", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `crying.json`.
    var cryingJson: RswiftResources.FileResource { .init(name: "crying", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `failed.json`.
    var failedJson: RswiftResources.FileResource { .init(name: "failed", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `lf20_tiviyc3p.json`.
    var lf20_tiviyc3pJson: RswiftResources.FileResource { .init(name: "lf20_tiviyc3p", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `oxford-5000.json`.
    var oxford5000Json: RswiftResources.FileResource { .init(name: "oxford-5000", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `paper-firework.json`.
    var paperFireworkJson: RswiftResources.FileResource { .init(name: "paper-firework", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `phrasal-verbs.json`.
    var phrasalVerbsJson: RswiftResources.FileResource { .init(name: "phrasal-verbs", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `sad-emoji.json`.
    var sadEmojiJson: RswiftResources.FileResource { .init(name: "sad-emoji", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 12 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `IconTextView`.
    var iconTextView: RswiftResources.NibReference<IconTextView> { .init(name: "IconTextView", bundle: bundle) }

    /// Nib `NoDataTableCell`.
    var noDataTableCell: RswiftResources.NibReferenceReuseIdentifier<NoDataTableCell, NoDataTableCell> { .init(name: "NoDataTableCell", bundle: bundle, identifier: "NoDataTableCell") }

    /// Nib `PracticeDescriptionForm`.
    var practiceDescriptionForm: RswiftResources.NibReference<PracticeDescriptionForm> { .init(name: "PracticeDescriptionForm", bundle: bundle) }

    /// Nib `PracticeTermForm`.
    var practiceTermForm: RswiftResources.NibReference<PracticeTermForm> { .init(name: "PracticeTermForm", bundle: bundle) }

    /// Nib `SetHeaderTableView`.
    var setHeaderTableView: RswiftResources.NibReference<SetHeaderTableView> { .init(name: "SetHeaderTableView", bundle: bundle) }

    /// Nib `SignInNoteView`.
    var signInNoteView: RswiftResources.NibReference<SignInNoteView> { .init(name: "SignInNoteView", bundle: bundle) }

    /// Nib `TermActivitiesTableCell`.
    var termActivitiesTableCell: RswiftResources.NibReference<TermActivitiesTableCell> { .init(name: "TermActivitiesTableCell", bundle: bundle) }

    /// Nib `TermActivityCollectionCell`.
    var termActivityCollectionCell: RswiftResources.NibReference<TermActivityCollectionCell> { .init(name: "TermActivityCollectionCell", bundle: bundle) }

    /// Nib `TextCollectionCell`.
    var textCollectionCell: RswiftResources.NibReference<TextCollectionCell> { .init(name: "TextCollectionCell", bundle: bundle) }

    /// Nib `TextTableCell`.
    var textTableCell: RswiftResources.NibReferenceReuseIdentifier<TextTableCell, TextTableCell> { .init(name: "TextTableCell", bundle: bundle, identifier: "TextTableCell") }

    /// Nib `TopicInRoutineTableCell`.
    var topicInRoutineTableCell: RswiftResources.NibReference<TopicInRoutineTableCell> { .init(name: "TopicInRoutineTableCell", bundle: bundle) }

    /// Nib `TopicTableViewCell`.
    var topicTableViewCell: RswiftResources.NibReference<TopicTableViewCell> { .init(name: "TopicTableViewCell", bundle: bundle) }

    func validate() throws {
      if UIKit.UIImage(named: "2", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named '2' is used in nib 'IconTextView', but couldn't be loaded.") }
      if UIKit.UIColor(named: "mainBackground", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'mainBackground' is used in nib 'PracticeDescriptionForm', but couldn't be loaded.") }
      if UIKit.UIColor(named: "active", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'active' is used in nib 'PracticeTermForm', but couldn't be loaded.") }
      if UIKit.UIColor(named: "mainBackground", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'mainBackground' is used in nib 'PracticeTermForm', but couldn't be loaded.") }
      if UIKit.UIImage(named: "folderIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'folderIcon' is used in nib 'SetHeaderTableView', but couldn't be loaded.") }
      if UIKit.UIImage(named: "moreActionIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'moreActionIcon' is used in nib 'SetHeaderTableView', but couldn't be loaded.") }
      if UIKit.UIColor(named: "mainText", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'mainText' is used in nib 'SetHeaderTableView', but couldn't be loaded.") }
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "multiply.circle.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'multiply.circle.fill' is used in nib 'SignInNoteView', but couldn't be loaded.") } }
      if UIKit.UIColor(named: "cellBackground", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'cellBackground' is used in nib 'TermActivityCollectionCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "active", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'active' is used in nib 'TextTableCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "calendarLineIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'calendarLineIcon' is used in nib 'TopicTableViewCell', but couldn't be loaded.") }
    }
  }

  /// This `_R.reuseIdentifier` struct is generated, and contains static references to 11 reuse identifiers.
  struct reuseIdentifier {

    /// Reuse identifier `HomeMenuTableViewCell`.
    let homeMenuTableViewCell: RswiftResources.ReuseIdentifier<HomeMenuTableViewCell> = .init(identifier: "HomeMenuTableViewCell")

    /// Reuse identifier `LogoutTableCell`.
    let logoutTableCell: RswiftResources.ReuseIdentifier<LogoutTableCell> = .init(identifier: "LogoutTableCell")

    /// Reuse identifier `NoDataTableCell`.
    let noDataTableCell: RswiftResources.ReuseIdentifier<NoDataTableCell> = .init(identifier: "NoDataTableCell")

    /// Reuse identifier `PracticeResultTableViewCell`.
    let practiceResultTableViewCell: RswiftResources.ReuseIdentifier<PracticeResultTableViewCell> = .init(identifier: "PracticeResultTableViewCell")

    /// Reuse identifier `ReviewCardCollectionCell`.
    let reviewCardCollectionCell: RswiftResources.ReuseIdentifier<ReviewCardCollectionCell> = .init(identifier: "ReviewCardCollectionCell")

    /// Reuse identifier `SetTableViewCell`.
    let setTableViewCell: RswiftResources.ReuseIdentifier<SetTableViewCell> = .init(identifier: "SetTableViewCell")

    /// Reuse identifier `SortedByMenuCell`.
    let sortedByMenuCell: RswiftResources.ReuseIdentifier<SortedByMenuCell> = .init(identifier: "SortedByMenuCell")

    /// Reuse identifier `TermCollectionCell`.
    let termCollectionCell: RswiftResources.ReuseIdentifier<TermCollectionCell> = .init(identifier: "TermCollectionCell")

    /// Reuse identifier `TermTableCell`.
    let termTableCell: RswiftResources.ReuseIdentifier<TermTableCell> = .init(identifier: "TermTableCell")

    /// Reuse identifier `TextTableCell`.
    let textTableCell: RswiftResources.ReuseIdentifier<TextTableCell> = .init(identifier: "TextTableCell")

    /// Reuse identifier `UserAvatarAndUserNameCell`.
    let userAvatarAndUserNameCell: RswiftResources.ReuseIdentifier<UserAvatarAndUserNameCell> = .init(identifier: "UserAvatarAndUserNameCell")
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var home: home { .init(bundle: bundle) }
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var popupStoryboard: popupStoryboard { .init(bundle: bundle) }

    func home(bundle: Foundation.Bundle) -> home {
      .init(bundle: bundle)
    }
    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func popupStoryboard(bundle: Foundation.Bundle) -> popupStoryboard {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.home.validate()
      try self.launchScreen.validate()
      try self.popupStoryboard.validate()
    }


    /// Storyboard `Home`.
    struct home: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "Home"

      var allTopicsViewController: RswiftResources.StoryboardViewControllerIdentifier<AllTopicsViewController> { .init(identifier: "AllTopicsViewController", storyboard: name, bundle: bundle) }
      var folderViewController: RswiftResources.StoryboardViewControllerIdentifier<FolderViewController> { .init(identifier: "FolderViewController", storyboard: name, bundle: bundle) }
      var launchViewController: RswiftResources.StoryboardViewControllerIdentifier<LaunchViewController> { .init(identifier: "LaunchViewController", storyboard: name, bundle: bundle) }
      var learnTopicViewController: RswiftResources.StoryboardViewControllerIdentifier<LearnTopicViewController> { .init(identifier: "LearnTopicViewController", storyboard: name, bundle: bundle) }
      var newFolderInputViewController: RswiftResources.StoryboardViewControllerIdentifier<NewFolderInputViewController> { .init(identifier: "NewFolderInputViewController", storyboard: name, bundle: bundle) }
      var practiceTopicViewController: RswiftResources.StoryboardViewControllerIdentifier<PracticeTopicViewController> { .init(identifier: "PracticeTopicViewController", storyboard: name, bundle: bundle) }
      var reviewCardViewController: RswiftResources.StoryboardViewControllerIdentifier<ReviewCardViewController> { .init(identifier: "ReviewCardViewController", storyboard: name, bundle: bundle) }
      var signInViewController: RswiftResources.StoryboardViewControllerIdentifier<SignInViewController> { .init(identifier: "SignInViewController", storyboard: name, bundle: bundle) }
      var signUpViewController: RswiftResources.StoryboardViewControllerIdentifier<SignUpViewController> { .init(identifier: "SignUpViewController", storyboard: name, bundle: bundle) }
      var sortedByMenuViewController: RswiftResources.StoryboardViewControllerIdentifier<SortedByMenuViewController> { .init(identifier: "SortedByMenuViewController", storyboard: name, bundle: bundle) }
      var termsViewController: RswiftResources.StoryboardViewControllerIdentifier<TermsViewController> { .init(identifier: "TermsViewController", storyboard: name, bundle: bundle) }
      var testTopicViewController: RswiftResources.StoryboardViewControllerIdentifier<TestTopicViewController> { .init(identifier: "TestTopicViewController", storyboard: name, bundle: bundle) }
      var topicsListViewController: RswiftResources.StoryboardViewControllerIdentifier<TopicsListViewController> { .init(identifier: "TopicsListViewController", storyboard: name, bundle: bundle) }
      var userInfoViewController: RswiftResources.StoryboardViewControllerIdentifier<UserInfoViewController> { .init(identifier: "UserInfoViewController", storyboard: name, bundle: bundle) }
      var viewController: RswiftResources.StoryboardViewControllerIdentifier<ViewController> { .init(identifier: "ViewController", storyboard: name, bundle: bundle) }

      func validate() throws {
        if UIKit.UIImage(named: "createDateIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'createDateIcon' is used in storyboard 'Home', but couldn't be loaded.") }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "eye.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'eye.fill' is used in storyboard 'Home', but couldn't be loaded.") } }
        if UIKit.UIImage(named: "fullIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'fullIcon' is used in storyboard 'Home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "paperIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'paperIcon' is used in storyboard 'Home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "trashLineIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'trashLineIcon' is used in storyboard 'Home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "victoryIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'victoryIcon' is used in storyboard 'Home', but couldn't be loaded.") }
        if UIKit.UIColor(named: "active", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'active' is used in storyboard 'Home', but couldn't be loaded.") }
        if UIKit.UIColor(named: "cellBackground", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'cellBackground' is used in storyboard 'Home', but couldn't be loaded.") }
        if UIKit.UIColor(named: "mainBackground", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'mainBackground' is used in storyboard 'Home', but couldn't be loaded.") }
        if UIKit.UIColor(named: "mainText", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'mainText' is used in storyboard 'Home', but couldn't be loaded.") }
        if allTopicsViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'allTopicsViewController' could not be loaded from storyboard 'Home' as 'AllTopicsViewController'.") }
        if folderViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'folderViewController' could not be loaded from storyboard 'Home' as 'FolderViewController'.") }
        if launchViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'launchViewController' could not be loaded from storyboard 'Home' as 'LaunchViewController'.") }
        if learnTopicViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'learnTopicViewController' could not be loaded from storyboard 'Home' as 'LearnTopicViewController'.") }
        if newFolderInputViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'newFolderInputViewController' could not be loaded from storyboard 'Home' as 'NewFolderInputViewController'.") }
        if practiceTopicViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'practiceTopicViewController' could not be loaded from storyboard 'Home' as 'PracticeTopicViewController'.") }
        if reviewCardViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'reviewCardViewController' could not be loaded from storyboard 'Home' as 'ReviewCardViewController'.") }
        if signInViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'signInViewController' could not be loaded from storyboard 'Home' as 'SignInViewController'.") }
        if signUpViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'signUpViewController' could not be loaded from storyboard 'Home' as 'SignUpViewController'.") }
        if sortedByMenuViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'sortedByMenuViewController' could not be loaded from storyboard 'Home' as 'SortedByMenuViewController'.") }
        if termsViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'termsViewController' could not be loaded from storyboard 'Home' as 'TermsViewController'.") }
        if testTopicViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'testTopicViewController' could not be loaded from storyboard 'Home' as 'TestTopicViewController'.") }
        if topicsListViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'topicsListViewController' could not be loaded from storyboard 'Home' as 'TopicsListViewController'.") }
        if userInfoViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'userInfoViewController' could not be loaded from storyboard 'Home' as 'UserInfoViewController'.") }
        if viewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'viewController' could not be loaded from storyboard 'Home' as 'ViewController'.") }
      }
    }

    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }

    /// Storyboard `PopupStoryboard`.
    struct popupStoryboard: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "PopupStoryboard"

      var practicalResultViewController: RswiftResources.StoryboardViewControllerIdentifier<PracticalResultViewController> { .init(identifier: "PracticalResultViewController", storyboard: name, bundle: bundle) }
      var resultPopupViewController: RswiftResources.StoryboardViewControllerIdentifier<ResultPopupViewController> { .init(identifier: "ResultPopupViewController", storyboard: name, bundle: bundle) }
      var turnResultPopup: RswiftResources.StoryboardViewControllerIdentifier<TurnResultPopup> { .init(identifier: "TurnResultPopup", storyboard: name, bundle: bundle) }

      func validate() throws {
        if UIKit.UIImage(named: "happyFaceIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'happyFaceIcon' is used in storyboard 'PopupStoryboard', but couldn't be loaded.") }
        if UIKit.UIColor(named: "cellBackground", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'cellBackground' is used in storyboard 'PopupStoryboard', but couldn't be loaded.") }
        if UIKit.UIColor(named: "mainBackground", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'mainBackground' is used in storyboard 'PopupStoryboard', but couldn't be loaded.") }
        if practicalResultViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'practicalResultViewController' could not be loaded from storyboard 'PopupStoryboard' as 'PracticalResultViewController'.") }
        if resultPopupViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'resultPopupViewController' could not be loaded from storyboard 'PopupStoryboard' as 'ResultPopupViewController'.") }
        if turnResultPopup() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'turnResultPopup' could not be loaded from storyboard 'PopupStoryboard' as 'TurnResultPopup'.") }
      }
    }
  }
}