excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- EngWordTests
- "*.generated.swift"
disabled_rules:
- trailing_whitespace
- line_length
- type_name
- force_cast

variable_name:
max_length:
    warning: 45
    error: 60
min_length:
    warning: 1


